---
driver:
  name: vagrant
  customize:
    nictype1: virtio
    cpus: 2
    memory: 512

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.10.4

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[mh-opsworks-recipes::install-mh-base-packages]
      - recipe[mh-opsworks-recipes::install-utils]

  - name: nodejs
    run_list:
      - recipe[mh-opsworks-recipes::install-nodejs]

  - name: utils
    run_list:
      - recipe[mh-opsworks-recipes::install-utils]

  - name: user-creation
    run_list:
      - recipe[mh-opsworks-recipes::create-matterhorn-user]

  - name: storage-server
    run_list:
      - recipe[mh-opsworks-recipes::nfs-export]

  - name: ffmpeg
    run_list:
      - recipe[mh-opsworks-recipes::install-ffmpeg]
    attributes:
      vagrant_environment: true

  - name: nginx-proxy
    run_list:
      - recipe[mh-opsworks-recipes::configure-nginx-proxy]

  - name: nginx-engage-proxy
    run_list:
      - recipe[mh-opsworks-recipes::configure-engage-nginx-proxy]

  - name: sh-to-bash
    run_list:
      - recipe[mh-opsworks-recipes::set-bash-as-default-shell]

  - name: set-timezone
    run_list:
      - recipe[mh-opsworks-recipes::set-timezone]

  - name: populate-maven-cache
    run_list:
      - recipe[mh-opsworks-recipes::populate-maven-cache]
    attributes:
      vagrant_environment: true

  - name: install-awscli
    run_list:
      - recipe[mh-opsworks-recipes::install-awscli]
