---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.10.4

platforms:
  - name: ubuntu-14.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
    attributes:
