language: ruby
before_install:
  - gem install bundler -v 1.15.1
gemfile:
  - test/support/Gemfile
cache:
  - bundler
rvm:
  - 2.0.0
notifications:
  email:
    - false
script: BUNDLE_GEMFILE=test/support/Gemfile bundle exec foodcritic -f any .
